### ISSUE TITLE
Fix hosted-secret-part-get/set (js side)

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#14]
Use hostingData given by server upon login to perform hosted-secret-part-get and hosted-secret-part-set.

https://github.com/openpeer/op-identity-provider-server-php/issues/13

**Comment by cadorn** [comment]
@adriano-maljkovic Is this fixed?

**Comment by adriano-maljkovic** [comment]
@cadorn let's say yes, but the validation is commented out on Java side to speed up the testing process... I will create another ticket for that once we have a separate environment to test against...
