### ISSUE TITLE
Register identity.hookflash.me

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#17]
- register identity.hookflash.me with HCS on Lockbox instance using test client as Customer Portal.
- setup all the id provider configuration based on what Java returned as a result of provider-create

**Comment by cadorn** [comment]
@adriano-maljkovic Let's get the customer portal deployed and working on the new server and then register an application for identity.hookflash.me just as any client would.
