### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#2]
Everything I need to do from cloning this repo to setting up the different auth strategies to testing it.

**Comment by adriano-maljkovic** [comment]
After cloning the repo, you need to setup an apache server. You need MySQL and PHP installed. That should be enaugh to setup the server.

For the server to get a correct config file, you need to create one in the server/var/www/app/config/ directory. the config.php will know which config file to look at based on the name of the file and the domain the server is running on. For example, if you setup a localhost named idprovider.loc, you need to provide a config file named config_idprovider.loc.php for the server to function. There is an example config file in the repo which you can use to provide your own config files. 

While setting up the config file, pleas be aware that some oauth services won't work locally at all. For instance, for facebook oauth to function, you will need to setup a real server (using a real DNS).

For the testing, you can use our php test page which will call ajax posts to the server. It is positioned in the server/var/www/idprovider.com/public/test/ directory, so it can be accessed through a get request (using browser) with yourdomain/test. There you can choose a request template from the select box, and then fill it with some data. Hitting Go button should initiate the request to be sent to the server and in the lower text area the result will be displayed.

For you to be able to know which auth scenario needs which request sequence, you need the architecture documentation. You can get it here https://bitbucket.org/hookflash/hookflash-architecture (It will probably be on github soon, too). The file that holds the sequence diagrams is in the server_stuff/LoginSequences_IdentityProviderInternal.pdf.

If you want to know how to run javascript tests, please contact Andrej Solar on that matter.

Please feel free to ask any aditional questions.

**Comment by adriano-maljkovic** [comment]
Also, to setup the database, execute the server/var/www/app/setup/provider_db.sql
