### ISSUE TITLE
facebook login stuck

### ISSUE THREAD

**Issue by robin-raymond** [hookflash/obsolete.op-identity-provider-server-php#22]
If you login to facebook, it completes but window remains open and never completes. identity-login-complete notification never fires.

https://gist.github.com/robin-raymond/b4040d6699b7d5a4bc79

**Comment by cadorn** [comment]
Made some progress:

```
[Tue Sep 17 2013 04:39:56 GMT+0000 (UTC)] ["afterLogin",{"result":{"$domain":"idprovider-javascript.hookflash.me","$id":"175787","$handler":"identity","$method":"login","$epoch":"1379392738","loginState":"Succeeded","identity":{"accessToken":"facebook-100004505261615-1384576738-09ca0f4e65ddf7f90e28e8cfe2321f1058a7cb6f","accessSecret":"574551e571e128161d95ea7b4031bbafccfc1a7c","accessSecretExpires":1384576738,"updated":"1379349650"},"lockbox":{"reset":"false"}}}]
[Tue Sep 17 2013 04:39:56 GMT+0000 (UTC)] ["hostedIdentitySecretSet",{"result":{"$domain":"idprovider-javascript.hookflash.me","$id":"175787","$handler":"identity","$method":"login","$epoch":"1379392738","loginState":"Succeeded","identity":{"accessToken":"facebook-100004505261615-1384576738-09ca0f4e65ddf7f90e28e8cfe2321f1058a7cb6f","accessSecret":"574551e571e128161d95ea7b4031bbafccfc1a7c","accessSecretExpires":1384576738,"updated":"1379349650"},"lockbox":{"reset":"false"}}},null,null]
[Tue Sep 17 2013 04:39:56 GMT+0000 (UTC)] ["ERROR","hostedIdentitySecretSet@https://idprovider-javascript.hookflash.me/js/HF.js:1105\nafterLogin@https://idprovider-javascript.hookflash.me/js/HF.js:865\nsuccess@https://idprovider-javascript.hookflash.me/js/HF.js:848\nl@https://idprovider-javascript.hookflash.me/js/lib/jquery/jquery-1.8.3.min.js:2\nfireWith@https://idprovider-javascript.hookflash.me/js/lib/jquery/jquery-1.8.3.min.js:2\nT@https://idprovider-javascript.hookflash.me/js/lib/jquery/jquery-1.8.3.min.js:2\nr@https://idprovider-javascript.hookflash.me/js/lib/jquery/jquery-1.8.3.min.js:2\n[native code]"]
```

**Comment by cadorn** [comment]
@Adriano I pushed HF.js changes to https://github.com/openpeer/op-identity-provider-server-php/tree/newsetupmerge

We now get `{\"result\":{\"error\":{\"reason\":{\"$id\":500,\"#text\":\"INTERNAL_SERVER_ERROR\"}}}}` after posting to: https://hcs-javascript.hookflash.me/password2

Here are test links you can run assuming the timestamps have not expired:

```
curl -v --data "{\"request\":{\"$domain\":\"idprovider-javascript.hookflash.me\",\"$id\":\"594790\",\"$handler\":\"identity\",\"$method\":\"hosted-identity-secret-part-set\",\"nonce\":\"c3f613bc474936a4f6f73ce7bb24c00242827d78\",\"hostingProof\":\"3faba4af5fdbdc625e19ff279cd64d0ebd82bccc\",\"hostingProofExpires\":1379559737,\"clientNonce\":\"674319\",\"identity\":{\"accessToken\":\"facebook-100004505261615-1384657336-afb41c365dfab08b20d5326dc6e393c3ff5b7087\",\"accessSecretProof\":\"f83587d1c01bbdbc9086a4200f58352225e7ef35\",\"accessSecretProofExpires\":1384657336,\"uri\":\"identity://facebook.com/100004505261615\",\"secretPart\":\"b910d967ac6ac8c9653ce20e65d1f079f9a73808\"}}}" https://hcs-javascript.hookflash.me/password1

curl -v --data "{\"request\":{\"$domain\":\"idprovider-javascript.hookflash.me\",\"$id\":\"594790\",\"$handler\":\"identity\",\"$method\":\"hosted-identity-secret-part-set\",\"nonce\":\"c3f613bc474936a4f6f73ce7bb24c00242827d78\",\"hostingProof\":\"3faba4af5fdbdc625e19ff279cd64d0ebd82bccc\",\"hostingProofExpires\":1379559737,\"clientNonce\":\"674319\",\"identity\":{\"accessToken\":\"facebook-100004505261615-1384657336-afb41c365dfab08b20d5326dc6e393c3ff5b7087\",\"accessSecretProof\":\"f83587d1c01bbdbc9086a4200f58352225e7ef35\",\"accessSecretProofExpires\":1384657336,\"uri\":\"identity://facebook.com/100004505261615\",\"secretPart\":\"b910d967ac6ac8c9653ce20e65d1f079f9a73808\"}}}" https://hcs-javascript.hookflash.me/password2
```

**Comment by cadorn** [comment]
Fixed curl call:

  curl -v -H "Content-Type: application/json" --data '{"request":{"$domain":"idprovider-javascript.hookflash.me","$id":"594790","$handler":"identity","$method":"hosted-identity-secret-part-set","nonce":"c3f613bc474936a4f6f73ce7bb24c00242827d78","hostingProof":"3faba4af5fdbdc625e19ff279cd64d0ebd82bccc","hostingProofExpires":1379559737,"clientNonce":"674319","identity":{"accessToken":"facebook-100004505261615-1384657336-afb41c365dfab08b20d5326dc6e393c3ff5b7087","accessSecretProof":"f83587d1c01bbdbc9086a4200f58352225e7ef35","accessSecretProofExpires":1384657336,"uri":"identity://facebook.com/100004505261615","secretPart":"b910d967ac6ac8c9653ce20e65d1f079f9a73808","secretSalt":"b910d967ac6ac8c9653ce20e65d1f079f9a73808"}}}' https://hcs-javascript.hookflash.me/password1

**Comment by cadorn** [comment]
@adriano-maljkovic 
I pushed and uploaded the fixes we discussed: https://github.com/openpeer/op-identity-provider-server-php/commit/ecaa71f2bbe19c03e216cf097f3c2cbf1b39bd0f

I think the secretSalt value is wrong tough? Should it not come from the first arg passed to `generateSecretPart`?

**Comment by adriano-maljkovic** [comment]
https://gist.github.com/adriano-maljkovic/6622522

**Comment by adriano-maljkovic** [comment]
@cadorn there is an Invalid Array Length error now. I can't see what's wrong...

**Comment by cadorn** [comment]
@adriano-maljkovic @robin-raymond Update:
- I fixed rolodex token encryption in PHP to be compatible with rolodex
- Client is now calling rolodex and seems to be authenticating

2 problems:

 1) The facebook API token robin's account was given is expired (or I think it is for some reason). I send a 424 error back to client which should then call http://docs.openpeer.org/OpenPeerProtocolSpecificationAnnexRolodex/#IdentityServiceRequestsAnnex-IdentityAccessRolodexCredentialsGetRequest **we need a flag in this request to force a re-oauth to go back to facebook and get a new API token** Generating new rolodex token with same facebook API key is not sufficient.

 2) If lockbox key is found and we go through https://github.com/openpeer/op-identity-provider-server-php/blob/12fef77d5338ebc80d4d505be15cd1872c0461c0/server/var/www/idprovider.com/public/js/HF.js#L1193 it sends a wrong request.

**Comment by adriano-maljkovic** [comment]
I added the support inside the JS side for the flag in case of expired access token. Client just needs to send a standard identity-access-rolodex-credentials-get with "oauthTokenExpired": true.

!!! BUT !!!
1) it won't work unless the inner frame is alive all the way from the last identity-access-start notification, since it needs the data from that request.
2) It will end up as a standard identity-access scenario resulting with identity-access-complete is being posted from inner frame to client. @robin-raymond please check if this will lead to an un-consistent client state.
- Another way of treating this issue would be this: Once Rolodex doubts the token validity, it informs the client, and then client only starts the standard login scenario with notifying identity-access-start.

**Comment by robin-raymond** [comment]
I can't imagine the token expires upon first login. Something else might be wrong. We might need to handle this scenario, but can you verify this is the trouble?

**Comment by cadorn** [comment]
Lets forget about (1). It updates the token every time it goes to idprovider for oauth so no need to send a special flag. So if client gets a 424, just go through the whole idprovider outh process again and then call IdentityAccessRolodexCredentialsGetRequest

**Comment by cadorn** [comment]
@robin-raymond  DB table column storing access token was too short and thus I was using a truncated token which facebook deemed invalid. Fixed now.

**Comment by cadorn** [comment]
Fixed!

**Comment by adriano-maljkovic** [comment]
It's alright to close the issue, since facebook is now working. But, we definitelly need a way to get the new token in case the old one expired. Rolodex will need a way to inform the client that the token is invalid due expiry, and thus Core should initiate the login via facebook sequence. We should definitelly handle this, too, but with a priority of a side-scenario.
