### ISSUE TITLE
Handle Sign-up With Existing User

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#23]
If existing username is sent in a sign-up request, the server will respond in:

{
    "result": {
        "$domain": "provider.com",
        "$id": "abc",
        "$handler": "identity-provider",
        "$method": "sign-up",
        "$epoch": "1380547206",
        "error": {
            "reason": {
                "$id": "403",
                "message": "Identity already exists: identity of type: 'federated' with identifier: 'adi' cannot be created."
            }
        }
    }
}

Please, return this error message to client.

**Comment by cadorn** [comment]
@robin-raymond Fixed. Please try.

**Comment by robin-raymond** [comment]
@cadorn yes, works, error messages need to be tidied on UI though

**Comment by cadorn** [comment]
UI cleanup is tracked in #28
