### ISSUE TITLE
Parameter Name Not Being Sent On Sign-up

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#26]
Here is identity service's behavior:
https://gist.github.com/robin-raymond/365ba504527e4dfe328c

The "name" field is returned empty because it is not set in the database. It can be set only upon sign-up on identity provider, when identity provider sends hosted-identity-update. That request is checked and works correctly.

So, the issue is most probably that JS does not send "name" to PHP service on sign-up.

Example sign-up with "displayName":
{
    "request": {
        "$domain": "provider.com",
        "$id": "abc",
        "$handler": "identity-provider",
        "$method": "sign-up",

```
    "identity": {
        "type": "federated",
        "identifier": "adriano",
        "passwordHash": "adjfhgqiu4rt346ruyegurfguaiy4tr4",
        "secretSalt": "hwyuig5yg5tjhsvrktyg5jgk5ygt54",
        "serverPasswordSalt": "wuiywg5tg765tiuysut6tsuygrtuue45",

        "displayName": "Adriano Maljkovic"
    }
}
```

}
- Please note: in JS<->PHP communication it is still called "displayName", but it's the same thing as "name" on Java side.

**Comment by cadorn** [comment]
@robin-raymond Should be fixed. Signup new federated identity and the name should come through.

**Comment by robin-raymond** [comment]
Resolved.
