### ISSUE TITLE
Implement `identity-access-rolodex-credentials-get`

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#3]
See: http://docs.openpeer.org/OpenPeerProtocolSpecificationAnnexRolodex/#IdentityServiceRequestsAnnex-IdentityAccessRolodexCredentialsGetRequest

**Comment by adriano-maljkovic** [comment]
@cadorn, how do I generate the serverToken to be returned as a result? How is it gonna be used? I suppose the middle section of it is a timestamp, but what is the first and the third one?

Thanks in advance

**Comment by cadorn** [comment]
Something like:

```
<sharedSecret> = hash (32 char)

<iv> = MD5 random hash (32 char)
token = <iv> + "-" + AES.encrypt(<sharedSecret>, <iv>, <credentials>)

<credentials> = JSON.stringify({
    service: <name (github|twitter|linkedin|facebook)>
    consumer_key: <OAuth consumer/api key provided by service>,
    consumer_secret: <OAuth consumer/api secret provided by service>,
    token: <OAuth access token>,
    token_secret: <OAuth access token secret>
})
```

For github and facebook we just need the `token` so the other fields can stay blank or can be omitted.

The `<sharedSecret>` we put in the configuration file of the identity provider and rolodex.

@robin-raymond We should probably codify this in the spec so we can ensure identity providers and rolodexes are compatible.

**Comment by adriano-maljkovic** [comment]
As set in the documentation, in the request, under identity data set, the outer frame sends the "provider" tag among others. That provider tag is not needed in this situation.

Clarification: It is only needed when an identity access validation is being used through an HCS service in order for the service to know with which identity provider to perform the validation. However, when the validation is sent to the identity provider directly, there is no need for specifying this, since the domain that is being set there is the actual domain the request is being sent to.

**Comment by adriano-maljkovic** [comment]
I finished it for facebook. Haven't had a chance to try it, since we are facing some server issues with permissions today.

**Comment by adriano-maljkovic** [comment]
Done for LinkedIn, too.

**Comment by adriano-maljkovic** [comment]
Maybe there can come some issues out with the encrypt/decrypt process. FYI, I'm using these:

```
    /**
 * Encrypts given value using secret key
 *
 * @param string $sValue Value to be encrypted
 * @param string $sSecretKey Key to be used for encryption
 * @return string 
 */
public function encrypt($sValue, $sSecretKey)
{
    return rtrim(
        base64_encode(
            mcrypt_encrypt(
                MCRYPT_RIJNDAEL_256,
                $sSecretKey, $sValue, 
                MCRYPT_MODE_ECB, 
                mcrypt_create_iv(
                    mcrypt_get_iv_size(
                        MCRYPT_RIJNDAEL_256, 
                        MCRYPT_MODE_ECB
                    ), 
                    MCRYPT_RAND)
                )
            ), "\0"
        );
}

/**
 * Decrypts given value using secret key
 *
 * @param string $sValue Value to be decrypted
 * @param string $sSecretKey Key to be used for decryption
 * @return string 
 */
public function decrypt($sValue, $sSecretKey)
{
    return rtrim(
        mcrypt_decrypt(
            MCRYPT_RIJNDAEL_256, 
            $sSecretKey, 
            base64_decode($sValue), 
            MCRYPT_MODE_ECB,
            mcrypt_create_iv(
                mcrypt_get_iv_size(
                    MCRYPT_RIJNDAEL_256,
                    MCRYPT_MODE_ECB
                ), 
                MCRYPT_RAND
            )
        ), "\0"
    );
}
```

**Comment by adriano-maljkovic** [comment]
@cadorn This won't work, There is a bug in the encrypt/decrypt functions I'm using. Will have to finish tomorrow...

**Comment by cadorn** [comment]
You need to prefix the `<iv>` to the token as you need to use the same IV during decryption.

**Comment by adriano-maljkovic** [comment]
@cadorn - done, you can try :)

**Comment by cadorn** [comment]
@adriano-maljkovic Where can I find the shared secret?

**Comment by cadorn** [comment]
@adriano-maljkovic What is the format of the token? Does it follow this:?

```
<sharedSecret> = hash (32 char)

<iv> = MD5 random hash (32 char)
token = <iv> + "-" + base64encode(AES.encrypt(<sharedSecret>, <iv>, <credentials>))

<credentials> = JSON.stringify({
    service: <name (github|twitter|linkedin|facebook)>
    consumer_key: <OAuth consumer/api key provided by service>,
    consumer_secret: <OAuth consumer/api secret provided by service>,
    token: <OAuth access token>,
    token_secret: <OAuth access token secret>
})
```

**Comment by cadorn** [comment]
@adriano-maljkovic See hipchat HCS room for more details.

**Comment by cadorn** [comment]
@adriano-maljkovic @robin-raymond did you get the encryption/decryption working between PHP and C/OpenSSL?

**Comment by adriano-maljkovic** [comment]
Strange, I don't remember being notified for this comment...
@cadorn no, still not. I did implement stuff like you showed in the crypto.php and was able to encrypt/decrypt myself, and with that I mean that I had the same results as you for the example on HCS.

**Comment by adriano-maljkovic** [comment]
Done
