### ISSUE TITLE
If facebook API token working don't oauth again on relogin

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#30]

**Comment by cadorn** [comment]
@adriano-maljkovic What do you think about @no-glue tackling this with your support?

**Comment by adriano-maljkovic** [comment]
@cadorn Seems regular to me. @no-glue Setup a meeting, we can go through the steps before you start implementing.

**Comment by adriano-maljkovic** [comment]
Assigning to @no-glue
