### ISSUE TITLE
Re-skin to look same as opios sample app

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#36]
@elagerway Where can I find the design files?

**Comment by elagerway** [comment]
@SergioOpenPeer can help you out with that

**Comment by elagerway** [comment]
https://github.com/openpeer/opios/tree/master/Samples/OpenPeerSampleApp/OpenPeerSampleApp/Images

**Comment by cadorn** [comment]
The background is now the same and debug info is gone.

@SergioOpenPeer @robin-raymond If you append `?dev=true` to the outer frame URLs you can get the debug display back

@elagerway If you want further skinning (input fields, buttons etc .. for federated login we can get alexey to do it.
