### ISSUE TITLE
Streamline browser visibility

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#37]
Browser visible notification seems to get sent when not needed after facebook oauth.

Notification may also be sent too early before facebook oauth.

Another notification may get sent later with the grant service when already granted. (depends on https://github.com/openpeer/op-identity-provider-server-php/issues/38)

**Comment by adriano-maljkovic** [comment]
@cadorn it is supposed to be sent every time there is a possibility that it is set to invisible, but we need to have an interaction with user. Such as on oauth login scenario, on federated login scenario, or on nemaspace grant scenarios. However, it should be called to set visible=false on legacy e-mail or legacy-phone scenarios which will come shortly...

@robin-raymond please check my states ^

**Comment by cadorn** [comment]
> Notification may also be sent too early before facebook oauth.

Not true. It is sent just before.

**Comment by cadorn** [comment]
Before I can test

> Another notification may get sent later with the grant service when already granted.

I need: https://github.com/openpeer/op-identity-provider-server-php/issues/38

**Comment by cadorn** [comment]
> Browser visible notification seems to get sent when not needed after facebook oauth.

Not true. No visible notification is sent again until for grant service.

**Comment by cadorn** [comment]
@elagerway It seems like first facebook login sequence is as fast as possible in terms of taking code paths. Re-login I cannot test until https://github.com/openpeer/op-identity-provider-server-php/issues/38 is fixed. We should get a 30% to 50% speedup after optimizing these pages which I can do after we have a new stack up and I have the opjs init sequence updated.

**Comment by elagerway** [comment]
looks good so far woot! :)

**Comment by cadorn** [comment]
good enough for now
