### ISSUE TITLE
Avatars on ID Provider

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#44]

**Comment by robin-raymond** [comment]
Can you provide more details on these kind of tickets so some one else reading knows what they are about? Thanks.

**Comment by adriano-maljkovic** [comment]
Some of the work is certainly done, so this ticket is regarding making sure these aren't missing:
- avatars need to be upload-able on sign-up page form
- mechanism to store avatars upon upload
- avatars parameter in `sign-up` API call (with it's support on both JS and PHP sides)
- avatars need it's space in identity provider's database
- avatars should be part of `hosted-identity-update` API call (called from provider to identity service)

**Comment by adriano-maljkovic** [comment]
fixed
