### ISSUE TITLE
ID provider .well-known/openpeer-services-get GET

### ISSUE THREAD

**Issue by robin-raymond** [hookflash/obsolete.op-identity-provider-server-php#48]
https://idprovider.com/.well-known/openpeer-services-get

This request should ALWAYS be hit as a GET request. The 302 redirect that happens after this request will be sent to a different URL whereupon a POST request will be issued with the original domain.

Thus for hosting scenarios, it will hit identity provider like this as a GET (without a "request" payload):
https://idprovider.com/.well-known/openpeer-services-get

(302 redirect reply to cloud service, like hcs.io)

Whereupon a POST is issued with the full "request" payload with the domain information as "idprovider.com":
https://hcs.io/services-get
^^^ NOTE: This URL is **NOT** under .well-known for hcs.io since it's NOT describing the 'well-known' information for HCS's service. 

This is necessary because it will be hard for developers to install PHP (or other stuff) under corporate "well-known" where scripting isn't always available.

For .well-known/openpeer-services-get under hcs.io you'd only have services described that are relevant to open peer services directly related to hcs.io exclusively (if any of those exist) and only include the entries that are relevant for hcs.io and not to any hosted service domains. If there is nothing to advertise it should return a 404.

**Comment by adriano-maljkovic** [comment]
@robin-raymond Let me sum up what I understand from this issue description.

The only differences are:
1. `services-get` on identity provider isn't being called by POST, but by GET.
2. `services-get` on HCS is going to be on `<hcs-domian>/services-get` instead of `<hcs-domain>/.wel-known/openpeer-services-get`.

And by this, I mean there is no difference in the result of the first `services-get`:

```
{
  "result": {
    "$domain": "<identity-domain>",
    "$handler": "bootstrapper",
    "$method": "services-get",

    "error": {
      "$id": 302,
      "#text": "Found",
      "location": "<hcs-domain>/services-get"
    }
  }
}
```

Please, correct me if I'm wrong.

**Comment by adriano-maljkovic** [comment]
php code complete by: https://github.com/openpeer/op-identity-provider-server-php/commit/a065a4f4097f19baae50d166221bc3a2f47eef96
test here: http://identity-v1-adriano-maljkovic-i.hcs.io/php/.well-known/openpeer-services-get.php
- Still need to add a proxy pass

**Comment by adriano-maljkovic** [comment]
added proxy: http://identity-v1-adriano-maljkovic-i.hcs.io/.well-known/openpeer-services-get

@robin-raymond If you agree with https://github.com/openpeer/op-identity-provider-server-php/issues/48#issuecomment-28693953, this issue is fixed. Thus, re-assigning back to you.

**Comment by cadorn** [comment]
Right; and `<hcs-domain>/.wel-known/openpeer-services-get` should return 404 if we don't need to advertise anything.

**Comment by robin-raymond** [comment]
@adriano-maljkovic correct summary, but @cadorn is right, we should return 404 on hcs domain if we don't advertise any services at all for the hcs domain or only return services we would advertise if someone did services-get on hcs domain for the hcs domain.

**Comment by adriano-maljkovic** [comment]
_"Right; and <hcs-domain>/.wel-known/openpeer-services-get should return 404 if we don't need to advertise anything."_
- this is already solved by a proper redirect on HCS - since the `.well-known` does not exist nor as page nor proxy on that server: http://hfservice-v1-adriano-maljkovic-i.hcs.io/.well-known/openpeer-services-get

**Comment by adriano-maljkovic** [comment]
@robin-raymond we agree on all aspects, implementation is in place - closing issue

**Comment by robin-raymond** [comment]
Search code for:

```
WARNING_SHOULD_BE_SENDING_AS_A_GET_REQUEST_NOT_A_POST
```

When this feature goes live.
