### ISSUE TITLE
Install PHP >= 5.4.

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#5]
Install PHP >= 5.4. on Lockbox instance in order for hex2bin() to be possible.

After that reassign back to me, so that I can refactor accordingly.

**Comment by predragmandic** [comment]
Installed **PHP 5.4.17** and **httpd24**. Everything works with exception to SSL when using private key with passphrase. When httpd is started it calls **/usr/libexec/httpd-ssl-pass-dialog** which is a script that wraps **/bin/systemd-ask-password** which doesn't exist on the system.

**Comment by adriano-maljkovic** [comment]
Fix the usage of hex/bin accordingly.
