### ISSUE TITLE
Test Page

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#51]
Create a new page at `/test-service` that I can hit with a POST request to test the identity provider setup.

It should try to connect to mysql and maybe do some other things and then return with 200 if ok or 500 if not.

**Comment by adriano-maljkovic** [comment]
@cadorn it is done by GET and is working on `/test/service.php`. Please provide the list of tests that need to be performed.

**Comment by cadorn** [comment]
POST should work too so I can force a reload of the page (in case request goes through a proxy).

Mysql test is good enough for now.

**Comment by cadorn** [comment]
@adriano-maljkovic Only return status `200` if ALL tests pass. If anything fails return status `500`.

**Comment by adriano-maljkovic** [comment]
@cadorn error status should now be in place. Still to support POST..

**Comment by adriano-maljkovic** [comment]
Fixed
