### ISSUE TITLE
Document: Identity Provider From The Eyes of a Customer

### ISSUE THREAD

**Issue by adriano-maljkovic** [hookflash/obsolete.op-identity-provider-server-php#59]
$feature #46

**Comment by elagerway** [comment]
That needs to happen on docs.hookflash.com

**Comment by elagerway** [comment]
@adriano-maljkovic I have sent you your credentials for docs.hookflash.com via passpack

**Comment by elagerway** [comment]
Also, let's not tackle OAuth right now, focus on customer DB integration.

**Comment by cadorn** [comment]
@adriano-maljkovic for the purpose of the docs, please use https://www.digitalocean.com and create a server using the [LAMP stack](https://www.digitalocean.com/features/one-click-apps/), then document everything you have to do to setup an ID provider connected to the mysql DB and register it in customer portal to downloading app in apptore and scanning QR code to hit hcs backend server configured in customer portal.

I will tie in the direction to the correct backend into the customer portal (https://github.com/hookflashco/hcs-stack/issues/46)

We should have credentials for digital ocean in passpack.

**Comment by elagerway** [comment]
Shared Dev, Live & Ops accounts via passpack for Digital Ocean with you @adriano-maljkovic

**Comment by adriano-maljkovic** [comment]
@elagerway I need access to the emails we use for digital cloud, we received root password there...

The e-mail I've used is:
`digitalocean-stage@hookflash.com`

**Comment by adriano-maljkovic** [comment]
_Update:_
- created droplet `example.identity.dev`
