### ISSUE TITLE
Refactoring/ Adding Profile options

### ISSUE THREAD

**Issue by OrahKokos** [hookflash/obsolete.op-identity-provider-server-php#61]
$feature https://github.com/openpeer/op-identity-provider-server-php/issues/46
- Profile get -> $related https://github.com/openpeer/op-identity-provider-server-php/issues/62
- Profile update -> $related https://github.com/openpeer/op-identity-provider-server-php/issues/63
- Password change (lockbox true) -> $related https://github.com/openpeer/op-identity-provider-server-php/issues/64
- Cloud contacts get -> $related https://github.com/openpeer/op-identity-provider-server-php/issues/65

**Comment by adriano-maljkovic** [comment]
$related #68
