### ISSUE TITLE
Document how to setup php identity provider server from scratch

### ISSUE THREAD

**Issue by arasbm** [hookflash/obsolete.op-identity-provider-server-php#71]
$feature https://github.com/hookflashco/hcs-stack/issues/49

Main doc page: http://docs.hookflash.com/display/09262013/Setting+up+identity+provider+examples+on+your+own+server

**Comment by arasbm** [comment]
I had a brainstorming session with @adriano-maljkovic and @Halve this morning about the paths we will provide in hookflash docs. We identify three different paths:
1. using preconfigured images 
   This will be a short section explaining that we have images ready for them to try and will point to https://github.com/hookflashco/hcs-stack-integration readme and maybe to an example homepage doc of one of our instances.
2. using our implementation of id provider and integrating their own database
   we would need to explain that after modifying they need to change persistence layer. Also we could suggest possible patterns they could follow to integrate their DB with ours. For example we may suggest that they use their own unique id to extend our data model. If we go down this path, we would need input from someone with deep knowledge of database integration.
3. implementing id provider server from scratch (based on their existing login system)
   In this path, we would mention that we have an example implementation on github that they can use as reference (PHP and later node). Then we would explain how they would **start from scratch** and implement their own identity provider server.

We agreed that the first and third path are essential, but we are not sure if we want to document and support the second path. @elagerway @cadorn we are wondering what you would recommend here. Should we proceed with all three paths, or should we drop the second path?

**Comment by elagerway** [comment]
I think we need to do whatever we can to make the integration and deployment of their id model as easy as possible and be as flexible as possible.  @robin-raymond what do u think?

**Comment by robin-raymond** [comment]
@arasbm @adriano-maljkovic I'd like to have a call at some point (either later today [after 6pm EST] or tomorrow) so I can understand exactly what you are trying to do. In general I agree with @elagerway 's comment but I'd like to understand better the "choices" being offered before I render an opinion.

**Comment by arasbm** [comment]
I'll try to provide a bit more background with my limited understanding. I had thought originally that the path for a customer to achieve a custom implementation of identity provider (on their own servers with own database and users) will start with cloning one of our identity provider examples and then tweaking it to get it to work with their own database. However, when talking to @adriano-maljkovic it sounds like we want them to start a project from scratch and implement identity provider. The concern being once they start using our identity provider implementations, we may get overwhelming support request (which may not be a bad thing?). If we get them to start with our implementation, they can skip a bunch of introductions about how to implement inner frame and outer frame and how the communication between them works. We will document that as well, but the concern here is about the path they will take through the docs.

I am not available after 5:30 today, but anytime tomorrow will work for me if you still like to meet to clarify this.

**Comment by arasbm** [comment]
After the meeting today, my understanding is that we are not focusing on documenting this path and instead we are creating example oAuth implementation here: https://github.com/hookflashco/hcs-stack-customer-oauth which will be the starting point for new clients trying to integrate their user base with our identity provider server.
