### ISSUE TITLE
Wrong redirect URL after login with `identity://facebook.com/`

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#8]
After posting to inner frame: https://gist.github.com/cadorn/9eb4d0e2337380da5fd0

And completing facebook oauth I get redirected to my outerFrameURL but with a request appended to it: `http://localhost:8081/test/stack/41-AccountFinder-Live&%7B%22result%22%3A%7B%22loginStat ...`

**Comment by adriano-maljkovic** [comment]
After the OAuth authentication success, no other redirections should happen, but the pure callback redirect (exact outer frame URL). The server could store the data inside the cookie, and just redirect back to the callback URL. After the outer frame initiates loading of the inner frame (which is on the same domain as the identity provider server) it can read the cookie and perform the login request using the data found inside the cookie.

@cadorn I will fix this asap.

**Comment by cadorn** [comment]
@adriano-maljkovic Where the the URL with the `reload=true` and various other parameters generated? Does facebook set that or do we? Where do we set the callback URL that facebook calls?

**Comment by adriano-maljkovic** [comment]
@cadorn 
"Where the the URL with the reload=true and various other parameters generated?"
- It is defined by openpeer spec. Check http://docs.openpeer.org/OpenPeerProtocolSpecification/#IdentityServiceRequests-IdentityAccessStartNotification as well as 
  http://docs.openpeer.org/OpenPeerProtocolSpecification/#NamespaceGrantServiceRequests-NamespaceGrantStartNotification

"Where do we set the callback URL that facebook calls?"
- It is defined upon creation of Facebook object in legacyOAuthLogin.php

**Comment by cadorn** [comment]
Added more logging calls so I can see what is going on.

**Comment by cadorn** [comment]
@adriano-maljkovic I have removed the need for the extra data in the reload URL.

Now the post-auth url is suffixed with `?reload=true&reload=true`. This needs to be removed as it is not needed any more. We should also remove the `?reload=true` from the URL in the spec.

Where is this reload=true still being set and why is it being set twice?

**Comment by adriano-maljkovic** [comment]
@cadorn Sorry, I didn't quite answer your last question above, I thought you mean "where the reload=true is set"... Anyway, I see you were able to find other parameters.

Now, about reload=true, please check with @robin-raymond. I believe there is a valid reason to have it... And, it's set in the inner frame, again, as part of the OP protocol. (However, I don't know exactly where)

**Comment by adriano-maljkovic** [comment]
@cadorn https://gist.github.com/adriano-maljkovic/6868249
- it's not outer frame bug
- it's not GUI side bug
- it's not core side bug
  So I'd say it must be inner frame bug - somewhere in var finishOAuthScenario = function(url) {...}

**Comment by elagerway** [comment]
Seeing this in the telnet logs, I suspect it's the same bug?

17:24:19.572399 W: <0x3bce818c> ServiceIdentity [] identity URI is not valid, uri=identity://facebook.com/ @stack_ServiceIdentitySession.cpp(2764) [isValid]

**Comment by robin-raymond** [comment]
@elagerway ignore that, it's not a proper identity uri, because it's an identity base uri, it's because we set to trace, and the lower level routine doesn't know if this is 'okay' or a 'problem', hence why it's a warning but it's totally fine.

**Comment by cadorn** [comment]
@robin-raymond Do you add `[&?]reload=true` to the URL? Why to we have to add that. We don't need it as we can keep a state in the identity provider session.

**Comment by cadorn** [comment]
I found one place where extra info is added. I'll see if it can be removed. https://github.com/openpeer/op-example-www-outer/blob/ba606ef36627192b49af0fa597e98ed5c71581ff/outer.js#L82

**Comment by adriano-maljkovic** [comment]
@cadorn That's it! I don't know how did it happen, but I definitely overlooked that, though I checked outer.js at least two times... Anyway, It's being set on GUI side, too. @robin-raymond Where is it more appropriate to be handled? Probably GUI, for then we can have outer.js nice and clean and focused on being a postman only?

**Comment by robin-raymond** [comment]
@adriano-maljkovic the ios app send the "url upon reload" as part of the messaging, so makes sense that it would append reload= as part of it's function and not do that in JS at all

**Comment by cadorn** [comment]
URL is clean now.
Tracking `reload=true` issue here #40
